// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: auth_user.proto

package resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthProviderEnum int32

const (
	AuthProviderEnum_google AuthProviderEnum = 0
)

// Enum value maps for AuthProviderEnum.
var (
	AuthProviderEnum_name = map[int32]string{
		0: "google",
	}
	AuthProviderEnum_value = map[string]int32{
		"google": 0,
	}
)

func (x AuthProviderEnum) Enum() *AuthProviderEnum {
	p := new(AuthProviderEnum)
	*p = x
	return p
}

func (x AuthProviderEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthProviderEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_user_proto_enumTypes[0].Descriptor()
}

func (AuthProviderEnum) Type() protoreflect.EnumType {
	return &file_auth_user_proto_enumTypes[0]
}

func (x AuthProviderEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthProviderEnum.Descriptor instead.
func (AuthProviderEnum) EnumDescriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{0}
}

type AuthUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Provider AuthProviderEnum `protobuf:"varint,1,opt,name=provider,proto3,enum=resources.AuthProviderEnum" json:"provider,omitempty"`
}

func (x *AuthUserRequest) Reset() {
	*x = AuthUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserRequest) ProtoMessage() {}

func (x *AuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserRequest.ProtoReflect.Descriptor instead.
func (*AuthUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{0}
}

func (x *AuthUserRequest) GetProvider() AuthProviderEnum {
	if x != nil {
		return x.Provider
	}
	return AuthProviderEnum_google
}

type AuthUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AuthUserResponse) Reset() {
	*x = AuthUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthUserResponse) ProtoMessage() {}

func (x *AuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthUserResponse.ProtoReflect.Descriptor instead.
func (*AuthUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_user_proto_rawDescGZIP(), []int{1}
}

func (x *AuthUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_auth_user_proto protoreflect.FileDescriptor

var file_auth_user_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x0f,
	0x41, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x37, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2a, 0x1e, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0a, 0x0a, 0x06, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x10, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_user_proto_rawDescOnce sync.Once
	file_auth_user_proto_rawDescData = file_auth_user_proto_rawDesc
)

func file_auth_user_proto_rawDescGZIP() []byte {
	file_auth_user_proto_rawDescOnce.Do(func() {
		file_auth_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_user_proto_rawDescData)
	})
	return file_auth_user_proto_rawDescData
}

var file_auth_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_user_proto_goTypes = []interface{}{
	(AuthProviderEnum)(0),    // 0: resources.AuthProviderEnum
	(*AuthUserRequest)(nil),  // 1: resources.AuthUserRequest
	(*AuthUserResponse)(nil), // 2: resources.AuthUserResponse
}
var file_auth_user_proto_depIdxs = []int32{
	0, // 0: resources.AuthUserRequest.provider:type_name -> resources.AuthProviderEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_user_proto_init() }
func file_auth_user_proto_init() {
	if File_auth_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_user_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_user_proto_goTypes,
		DependencyIndexes: file_auth_user_proto_depIdxs,
		EnumInfos:         file_auth_user_proto_enumTypes,
		MessageInfos:      file_auth_user_proto_msgTypes,
	}.Build()
	File_auth_user_proto = out.File
	file_auth_user_proto_rawDesc = nil
	file_auth_user_proto_goTypes = nil
	file_auth_user_proto_depIdxs = nil
}
