nats:
  hostname: "localhost"
  request:
    subject: "auth-request"
    queue: "robin"
secretsfolderpath: "secrets" 
auth:
  google:
    secretfilename: "google.json"
    redirecturl: "http://localhost:9000/auth"