version: "3.5"
services:
  nats:
    image: nats:2.2-scratch
    ports:
      - "4222:4222"
      - "6222:6222"
      - "1000:8222"
  
  roach-db:
    image: cockroachdb/cockroach:v21.1.2
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "1001:8080"
    volumes:
      - roach-db:/cockroach/cockroach-data
      
  robin:
    image: robin
    depends_on:
      - nats
      - roach-db

volumes:
  roach-db: