// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: auth_provider.proto

package proto_resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthProviderEnum int32

const (
	AuthProviderEnum_google AuthProviderEnum = 0
)

// Enum value maps for AuthProviderEnum.
var (
	AuthProviderEnum_name = map[int32]string{
		0: "google",
	}
	AuthProviderEnum_value = map[string]int32{
		"google": 0,
	}
)

func (x AuthProviderEnum) Enum() *AuthProviderEnum {
	p := new(AuthProviderEnum)
	*p = x
	return p
}

func (x AuthProviderEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthProviderEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_provider_proto_enumTypes[0].Descriptor()
}

func (AuthProviderEnum) Type() protoreflect.EnumType {
	return &file_auth_provider_proto_enumTypes[0]
}

func (x AuthProviderEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthProviderEnum.Descriptor instead.
func (AuthProviderEnum) EnumDescriptor() ([]byte, []int) {
	return file_auth_provider_proto_rawDescGZIP(), []int{0}
}

var File_auth_provider_proto protoreflect.FileDescriptor

var file_auth_provider_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x2a, 0x1e, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0a, 0x0a, 0x06, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x00,
	0x42, 0x12, 0x5a, 0x10, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_provider_proto_rawDescOnce sync.Once
	file_auth_provider_proto_rawDescData = file_auth_provider_proto_rawDesc
)

func file_auth_provider_proto_rawDescGZIP() []byte {
	file_auth_provider_proto_rawDescOnce.Do(func() {
		file_auth_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_provider_proto_rawDescData)
	})
	return file_auth_provider_proto_rawDescData
}

var file_auth_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_provider_proto_goTypes = []interface{}{
	(AuthProviderEnum)(0), // 0: resources.AuthProviderEnum
}
var file_auth_provider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_provider_proto_init() }
func file_auth_provider_proto_init() {
	if File_auth_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_provider_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_provider_proto_goTypes,
		DependencyIndexes: file_auth_provider_proto_depIdxs,
		EnumInfos:         file_auth_provider_proto_enumTypes,
	}.Build()
	File_auth_provider_proto = out.File
	file_auth_provider_proto_rawDesc = nil
	file_auth_provider_proto_goTypes = nil
	file_auth_provider_proto_depIdxs = nil
}
