name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2
      with:
        version: '3.x'

    - name: Setup protobuf generator for Golang
      run: go get -u github.com/golang/protobuf/{proto,protoc-gen-go}

    - name: Build protobuf
      run: sh scripts/build_proto.sh 

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Lint
        uses: golangci/golangci-lint-action@v2
