name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'

    - name: Build protobuf
      run: sh scripts/build_proto.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
